#!/usr/bin/env python3
"""Generate the Rust/Verus benchmark pilot dataset."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BENCH = ROOT / "benchmarks" / "rust-verus-problems"
GT = BENCH / "ground-truth"
REQ = BENCH / "requirements"


PRELUDE = "use vstd::prelude::*;\n\nverus! {\n\n"
POSTLUDE = "\n}\n\nfn main() {}\n"


def problem(
    id: int,
    category: str,
    filename: str,
    requirement: str,
    signature: str,
    clauses: list[tuple[str, str, str]],
    contract: str,
    body: str,
) -> dict:
    return {
        "id": id,
        "category": category,
        "filename": filename,
        "requirement_en": requirement,
        "function_signature": signature,
        "clauses": clauses,
        "contract": contract,
        "body": body,
    }


P: list[dict] = [
    problem(1, "scalar_arithmetic", "Problem001_MaxU64.rs", "Given two unsigned 64-bit integers, return the greater value without overflow or mutation.", "fn max_u64(x: u64, y: u64) -> u64;", [("ensures", "r == x || r == y", "result is one input"), ("ensures", "r >= x && r >= y", "result is at least both inputs")], "ensures r == x || r == y, r >= x && r >= y", "pub fn max_u64(x: u64, y: u64) -> (r: u64)\n    ensures\n        r == x || r == y,\n        r >= x && r >= y,\n{\n    if x >= y { x } else { y }\n}\n"),
    problem(2, "scalar_arithmetic", "Problem002_MinU64.rs", "Given two unsigned 64-bit integers, return the smaller value.", "fn min_u64(x: u64, y: u64) -> u64;", [("ensures", "r == x || r == y", "result is one input"), ("ensures", "r <= x && r <= y", "result is at most both inputs")], "ensures r == x || r == y, r <= x && r <= y", "pub fn min_u64(x: u64, y: u64) -> (r: u64)\n    ensures\n        r == x || r == y,\n        r <= x && r <= y,\n{\n    if x <= y { x } else { y }\n}\n"),
    problem(3, "scalar_arithmetic", "Problem003_ClampU64.rs", "Given a value and an inclusive valid range, return the value clamped into that range.", "fn clamp_u64(x: u64, lo: u64, hi: u64) -> u64;", [("requires", "lo <= hi", "range is ordered"), ("ensures", "lo <= r && r <= hi", "result lies in range"), ("ensures", "x < lo ==> r == lo", "low values clamp to lower bound"), ("ensures", "lo <= x && x <= hi ==> r == x", "in-range values are unchanged"), ("ensures", "x > hi ==> r == hi", "high values clamp to upper bound")], "requires lo <= hi; ensures lo <= r && r <= hi; ensures x < lo ==> r == lo; ensures lo <= x && x <= hi ==> r == x; ensures x > hi ==> r == hi", "pub fn clamp_u64(x: u64, lo: u64, hi: u64) -> (r: u64)\n    requires\n        lo <= hi,\n    ensures\n        lo <= r && r <= hi,\n        x < lo ==> r == lo,\n        lo <= x && x <= hi ==> r == x,\n        x > hi ==> r == hi,\n{\n    if x < lo { lo } else if x > hi { hi } else { x }\n}\n"),
    problem(4, "scalar_arithmetic", "Problem004_SafeAdd.rs", "Given two unsigned integers whose sum fits in u64, return their sum.", "fn safe_add(x: u64, y: u64) -> u64;", [("requires", "x <= u64::MAX - y", "addition cannot overflow"), ("ensures", "r == x + y", "result is mathematical sum")], "requires x <= u64::MAX - y; ensures r == x + y", "pub fn safe_add(x: u64, y: u64) -> (r: u64)\n    requires\n        x <= u64::MAX - y,\n    ensures\n        r == x + y,\n{\n    x + y\n}\n"),
    problem(5, "scalar_arithmetic", "Problem005_SafeSub.rs", "Given two unsigned integers where the subtrahend is not larger, return their difference.", "fn safe_sub(x: u64, y: u64) -> u64;", [("requires", "y <= x", "subtraction cannot underflow"), ("ensures", "r == x - y", "result is mathematical difference")], "requires y <= x; ensures r == x - y", "pub fn safe_sub(x: u64, y: u64) -> (r: u64)\n    requires\n        y <= x,\n    ensures\n        r == x - y,\n{\n    x - y\n}\n"),
    problem(6, "scalar_arithmetic", "Problem006_IncrementBounded.rs", "Given an unsigned integer smaller than u64::MAX, return it plus one.", "fn increment_bounded(x: u64) -> u64;", [("requires", "x < u64::MAX", "increment cannot overflow"), ("ensures", "r == x + 1", "result is incremented value")], "requires x < u64::MAX; ensures r == x + 1", "pub fn increment_bounded(x: u64) -> (r: u64)\n    requires\n        x < u64::MAX,\n    ensures\n        r == x + 1,\n{\n    x + 1\n}\n"),
    problem(7, "scalar_arithmetic", "Problem007_DecrementPositive.rs", "Given a positive unsigned integer, return it minus one.", "fn decrement_positive(x: u64) -> u64;", [("requires", "x > 0", "decrement cannot underflow"), ("ensures", "r == x - 1", "result is decremented value")], "requires x > 0; ensures r == x - 1", "pub fn decrement_positive(x: u64) -> (r: u64)\n    requires\n        x > 0,\n    ensures\n        r == x - 1,\n{\n    x - 1\n}\n"),
    problem(8, "scalar_arithmetic", "Problem008_AbsDiff.rs", "Given two unsigned integers, return their absolute difference without underflow.", "fn abs_diff_u64(x: u64, y: u64) -> u64;", [("ensures", "x >= y ==> r == x - y", "when x is larger result is x minus y"), ("ensures", "x < y ==> r == y - x", "when y is larger result is y minus x")], "ensures x >= y ==> r == x - y; ensures x < y ==> r == y - x", "pub fn abs_diff_u64(x: u64, y: u64) -> (r: u64)\n    ensures\n        x >= y ==> r == x - y,\n        x < y ==> r == y - x,\n{\n    if x >= y { x - y } else { y - x }\n}\n"),
    problem(9, "scalar_arithmetic", "Problem009_AverageFloor.rs", "Given two unsigned integers whose sum fits in u64, return floor((x + y) / 2).", "fn average_floor(x: u64, y: u64) -> u64;", [("requires", "x <= u64::MAX - y", "addition cannot overflow"), ("ensures", "r == (x + y) / 2", "result is floor average")], "requires x <= u64::MAX - y; ensures r == (x + y) / 2", "pub fn average_floor(x: u64, y: u64) -> (r: u64)\n    requires\n        x <= u64::MAX - y,\n    ensures\n        r == (x + y) / 2,\n{\n    (x + y) / 2\n}\n"),
    problem(10, "scalar_arithmetic", "Problem010_SaturatingSub.rs", "Given two unsigned integers, subtract the second from the first, returning zero on underflow.", "fn saturating_sub_u64(x: u64, y: u64) -> u64;", [("ensures", "x >= y ==> r == x - y", "normal subtraction when safe"), ("ensures", "x < y ==> r == 0", "underflow case saturates to zero")], "ensures x >= y ==> r == x - y; ensures x < y ==> r == 0", "pub fn saturating_sub_u64(x: u64, y: u64) -> (r: u64)\n    ensures\n        x >= y ==> r == x - y,\n        x < y ==> r == 0,\n{\n    if x >= y { x - y } else { 0 }\n}\n"),
]


P += [
    problem(11, "option_result", "Problem011_OptionIsSome.rs", "Given an Option<u64>, return true exactly when it contains a value.", "fn option_is_some(o: Option<u64>) -> bool;", [("ensures", "r <==> o is Some", "result reflects Some variant")], "ensures r <==> o is Some", "pub fn option_is_some(o: Option<u64>) -> (r: bool)\n    ensures\n        r <==> o is Some,\n{\n    match o { Option::Some(_) => true, Option::None => false }\n}\n"),
    problem(12, "option_result", "Problem012_OptionIsNone.rs", "Given an Option<u64>, return true exactly when it is None.", "fn option_is_none(o: Option<u64>) -> bool;", [("ensures", "r <==> o is None", "result reflects None variant")], "ensures r <==> o is None", "pub fn option_is_none(o: Option<u64>) -> (r: bool)\n    ensures\n        r <==> o is None,\n{\n    match o { Option::Some(_) => false, Option::None => true }\n}\n"),
    problem(13, "option_result", "Problem013_UnwrapOr.rs", "Given an Option<u64> and a default, return the contained value or the default.", "fn unwrap_or_u64(o: Option<u64>, default: u64) -> u64;", [("ensures", "o is Some ==> r == o->Some_0", "Some returns contained value"), ("ensures", "o is None ==> r == default", "None returns default")], "ensures o is Some ==> r == o->Some_0; ensures o is None ==> r == default", "pub fn unwrap_or_u64(o: Option<u64>, default: u64) -> (r: u64)\n    ensures\n        o is Some ==> r == o->Some_0,\n        o is None ==> r == default,\n{\n    match o { Option::Some(x) => x, Option::None => default }\n}\n"),
    problem(14, "option_result", "Problem014_OptionIncrement.rs", "Given an Option<u64>, increment the contained value when present and safe, otherwise keep None.", "fn option_increment(o: Option<u64>) -> Option<u64>;", [("requires", "o is Some ==> o->Some_0 < u64::MAX", "contained value can be incremented"), ("ensures", "o is None ==> r is None", "None remains None"), ("ensures", "o is Some ==> r is Some && r->Some_0 == o->Some_0 + 1", "Some value is incremented")], "requires o is Some ==> o->Some_0 < u64::MAX; ensures o is None ==> r is None; ensures o is Some ==> r is Some && r->Some_0 == o->Some_0 + 1", "pub fn option_increment(o: Option<u64>) -> (r: Option<u64>)\n    requires\n        o is Some ==> o->Some_0 < u64::MAX,\n    ensures\n        o is None ==> r is None,\n        o is Some ==> r is Some && r->Some_0 == o->Some_0 + 1,\n{\n    match o { Option::Some(x) => Option::Some(x + 1), Option::None => Option::None }\n}\n"),
    problem(15, "option_result", "Problem015_FilterNonzero.rs", "Given a u64, return Some(x) exactly when x is nonzero, otherwise None.", "fn filter_nonzero(x: u64) -> Option<u64>;", [("ensures", "x == 0 ==> r is None", "zero is rejected"), ("ensures", "x != 0 ==> r is Some && r->Some_0 == x", "nonzero is returned")], "ensures x == 0 ==> r is None; ensures x != 0 ==> r is Some && r->Some_0 == x", "pub fn filter_nonzero(x: u64) -> (r: Option<u64>)\n    ensures\n        x == 0 ==> r is None,\n        x != 0 ==> r is Some && r->Some_0 == x,\n{\n    if x == 0 { Option::None } else { Option::Some(x) }\n}\n"),
    problem(16, "option_result", "Problem016_BoolToResult.rs", "Given a boolean and value, return Ok(value) when the boolean is true and Err otherwise.", "fn bool_to_result(ok: bool, value: u64) -> Result<u64, ()>;", [("ensures", "ok ==> r is Ok && r->Ok_0 == value", "true returns Ok value"), ("ensures", "!ok ==> r is Err", "false returns Err")], "ensures ok ==> r is Ok && r->Ok_0 == value; ensures !ok ==> r is Err", "pub fn bool_to_result(ok: bool, value: u64) -> (r: Result<u64, ()>)\n    ensures\n        ok ==> r is Ok && r->Ok_0 == value,\n        !ok ==> r is Err,\n{\n    if ok { Result::Ok(value) } else { Result::Err(()) }\n}\n"),
    problem(17, "option_result", "Problem017_ResultIsOk.rs", "Given a Result<u64, ()>, return true exactly when it is Ok.", "fn result_is_ok(x: Result<u64, ()>) -> bool;", [("ensures", "r <==> x is Ok", "result reflects Ok variant")], "ensures r <==> x is Ok", "pub fn result_is_ok(x: Result<u64, ()>) -> (r: bool)\n    ensures\n        r <==> x is Ok,\n{\n    match x { Result::Ok(_) => true, Result::Err(_) => false }\n}\n"),
    problem(18, "option_result", "Problem018_ResultUnwrapOr.rs", "Given a Result<u64, ()> and a default, return the Ok value or the default.", "fn result_unwrap_or(x: Result<u64, ()>, default: u64) -> u64;", [("ensures", "x is Ok ==> r == x->Ok_0", "Ok returns contained value"), ("ensures", "x is Err ==> r == default", "Err returns default")], "ensures x is Ok ==> r == x->Ok_0; ensures x is Err ==> r == default", "pub fn result_unwrap_or(x: Result<u64, ()>, default: u64) -> (r: u64)\n    ensures\n        x is Ok ==> r == x->Ok_0,\n        x is Err ==> r == default,\n{\n    match x { Result::Ok(v) => v, Result::Err(_) => default }\n}\n"),
    problem(19, "option_result", "Problem019_CheckedAddOption.rs", "Given two unsigned integers, return Some(sum) when addition fits in u64 and None otherwise.", "fn checked_add_option(x: u64, y: u64) -> Option<u64>;", [("ensures", "x <= u64::MAX - y ==> r is Some && r->Some_0 == x + y", "safe addition returns Some sum"), ("ensures", "x > u64::MAX - y ==> r is None", "overflow returns None")], "ensures x <= u64::MAX - y ==> r is Some && r->Some_0 == x + y; ensures x > u64::MAX - y ==> r is None", "pub fn checked_add_option(x: u64, y: u64) -> (r: Option<u64>)\n    ensures\n        x <= u64::MAX - y ==> r is Some && r->Some_0 == x + y,\n        x > u64::MAX - y ==> r is None,\n{\n    if x <= u64::MAX - y { Option::Some(x + y) } else { Option::None }\n}\n"),
    problem(20, "option_result", "Problem020_SafeDivResult.rs", "Given two unsigned integers, return Ok(x / y) when y is nonzero and Err when y is zero.", "fn safe_div_result(x: u64, y: u64) -> Result<u64, ()>;", [("ensures", "y == 0 ==> r is Err", "division by zero returns Err"), ("ensures", "y != 0 ==> r is Ok && r->Ok_0 == x / y", "nonzero divisor returns quotient")], "ensures y == 0 ==> r is Err; ensures y != 0 ==> r is Ok && r->Ok_0 == x / y", "pub fn safe_div_result(x: u64, y: u64) -> (r: Result<u64, ()>)\n    ensures\n        y == 0 ==> r is Err,\n        y != 0 ==> r is Ok && r->Ok_0 == x / y,\n{\n    if y == 0 { Result::Err(()) } else { Result::Ok(x / y) }\n}\n"),
]


P += [
    problem(21, "vec_immutable", "Problem021_VecLen.rs", "Given an immutable borrowed Vec<u64>, return its length without mutation.", "fn vec_len(v: &Vec<u64>) -> usize;", [("ensures", "r == v.len()", "result is executable vector length"), ("ensures", "r == v@.len()", "result is ghost sequence length")], "ensures r == v.len(); ensures r == v@.len()", "pub fn vec_len(v: &Vec<u64>) -> (r: usize)\n    ensures\n        r == v.len(),\n        r == v@.len(),\n{\n    v.len()\n}\n"),
    problem(22, "vec_immutable", "Problem022_VecIsEmpty.rs", "Given an immutable borrowed Vec<u64>, return true exactly when its length is zero.", "fn vec_is_empty(v: &Vec<u64>) -> bool;", [("ensures", "r <==> v.len() == 0", "empty iff length is zero")], "ensures r <==> v.len() == 0", "pub fn vec_is_empty(v: &Vec<u64>) -> (r: bool)\n    ensures\n        r <==> v.len() == 0,\n{\n    v.len() == 0\n}\n"),
    problem(23, "vec_immutable", "Problem023_VecFirst.rs", "Given a nonempty borrowed Vec<u64>, return its first element without mutation.", "fn vec_first(v: &Vec<u64>) -> u64;", [("requires", "v.len() > 0", "vector is nonempty"), ("ensures", "r == v[0]", "result is first element")], "requires v.len() > 0; ensures r == v[0]", "pub fn vec_first(v: &Vec<u64>) -> (r: u64)\n    requires\n        v.len() > 0,\n    ensures\n        r == v[0],\n{\n    v[0]\n}\n"),
    problem(24, "vec_immutable", "Problem024_VecLast.rs", "Given a nonempty borrowed Vec<u64>, return its last element without mutation.", "fn vec_last(v: &Vec<u64>) -> u64;", [("requires", "v.len() > 0", "vector is nonempty"), ("ensures", "r == v[v.len() - 1]", "result is last element")], "requires v.len() > 0; ensures r == v[v.len() - 1]", "pub fn vec_last(v: &Vec<u64>) -> (r: u64)\n    requires\n        v.len() > 0,\n    ensures\n        r == v[v.len() - 1],\n{\n    v[v.len() - 1]\n}\n"),
    problem(25, "vec_immutable", "Problem025_VecGetAt.rs", "Given a borrowed Vec<u64> and a valid index, return the indexed element.", "fn vec_get_at(v: &Vec<u64>, i: usize) -> u64;", [("requires", "i < v.len()", "index is in bounds"), ("ensures", "r == v[i as int]", "result is indexed element")], "requires i < v.len(); ensures r == v[i as int]", "pub fn vec_get_at(v: &Vec<u64>, i: usize) -> (r: u64)\n    requires\n        i < v.len(),\n    ensures\n        r == v[i as int],\n{\n    v[i]\n}\n"),
    problem(26, "vec_immutable", "Problem026_VecGetOption.rs", "Given a borrowed Vec<u64> and an index, return Some(element) for in-bounds indices and None otherwise.", "fn vec_get_option(v: &Vec<u64>, i: usize) -> Option<u64>;", [("ensures", "i < v.len() ==> r is Some && r->Some_0 == v[i as int]", "valid index returns Some element"), ("ensures", "i >= v.len() ==> r is None", "invalid index returns None")], "ensures i < v.len() ==> r is Some && r->Some_0 == v[i as int]; ensures i >= v.len() ==> r is None", "pub fn vec_get_option(v: &Vec<u64>, i: usize) -> (r: Option<u64>)\n    ensures\n        i < v.len() ==> r is Some && r->Some_0 == v[i as int],\n        i >= v.len() ==> r is None,\n{\n    if i < v.len() { Option::Some(v[i]) } else { Option::None }\n}\n"),
    problem(27, "vec_immutable", "Problem027_VecHeadOrDefault.rs", "Given a borrowed Vec<u64> and a default, return the first element when present and the default otherwise.", "fn vec_head_or_default(v: &Vec<u64>, default: u64) -> u64;", [("ensures", "v.len() > 0 ==> r == v[0]", "nonempty vector returns first element"), ("ensures", "v.len() == 0 ==> r == default", "empty vector returns default")], "ensures v.len() > 0 ==> r == v[0]; ensures v.len() == 0 ==> r == default", "pub fn vec_head_or_default(v: &Vec<u64>, default: u64) -> (r: u64)\n    ensures\n        v.len() > 0 ==> r == v[0],\n        v.len() == 0 ==> r == default,\n{\n    if v.len() > 0 { v[0] } else { default }\n}\n"),
    problem(28, "vec_immutable", "Problem028_VecLastOrDefault.rs", "Given a borrowed Vec<u64> and a default, return the last element when present and the default otherwise.", "fn vec_last_or_default(v: &Vec<u64>, default: u64) -> u64;", [("ensures", "v.len() > 0 ==> r == v[v.len() - 1]", "nonempty vector returns last element"), ("ensures", "v.len() == 0 ==> r == default", "empty vector returns default")], "ensures v.len() > 0 ==> r == v[v.len() - 1]; ensures v.len() == 0 ==> r == default", "pub fn vec_last_or_default(v: &Vec<u64>, default: u64) -> (r: u64)\n    ensures\n        v.len() > 0 ==> r == v[v.len() - 1],\n        v.len() == 0 ==> r == default,\n{\n    if v.len() > 0 { v[v.len() - 1] } else { default }\n}\n"),
    problem(29, "vec_immutable", "Problem029_VecContains.rs", "Given a borrowed Vec<u64> and a target, return true exactly when some element equals the target.", "fn vec_contains(v: &Vec<u64>, target: u64) -> bool;", [("ensures", "r <==> exists|i:int| 0 <= i < v.len() && v[i] == target", "result iff target occurs")], "ensures r <==> exists|i:int| 0 <= i < v.len() && v[i] == target", "pub fn vec_contains(v: &Vec<u64>, target: u64) -> (r: bool)\n    ensures\n        r <==> exists|i: int| 0 <= i < v.len() && v[i] == target,\n{\n    let mut i: usize = 0;\n    while i < v.len()\n        invariant\n            0 <= i <= v.len(),\n            forall|j: int| 0 <= j < i ==> v[j] != target,\n        decreases v.len() - i,\n    {\n        if v[i] == target { return true; }\n        i += 1;\n    }\n    false\n}\n"),
    problem(30, "vec_immutable", "Problem030_VecAllNonzero.rs", "Given a borrowed Vec<u64>, return true exactly when every element is nonzero.", "fn vec_all_nonzero(v: &Vec<u64>) -> bool;", [("ensures", "r <==> forall|i:int| 0 <= i < v.len() ==> v[i] != 0", "result iff all elements are nonzero")], "ensures r <==> forall|i:int| 0 <= i < v.len() ==> v[i] != 0", "pub fn vec_all_nonzero(v: &Vec<u64>) -> (r: bool)\n    ensures\n        r <==> forall|i: int| 0 <= i < v.len() ==> v[i] != 0,\n{\n    let mut i: usize = 0;\n    while i < v.len()\n        invariant\n            0 <= i <= v.len(),\n            forall|j: int| 0 <= j < i ==> v[j] != 0,\n        decreases v.len() - i,\n    {\n        if v[i] == 0 { return false; }\n        i += 1;\n    }\n    true\n}\n"),
    problem(31, "vec_immutable", "Problem031_VecAnyZero.rs", "Given a borrowed Vec<u64>, return true exactly when at least one element is zero.", "fn vec_any_zero(v: &Vec<u64>) -> bool;", [("ensures", "r <==> exists|i:int| 0 <= i < v.len() && v[i] == 0", "result iff a zero occurs")], "ensures r <==> exists|i:int| 0 <= i < v.len() && v[i] == 0", "pub fn vec_any_zero(v: &Vec<u64>) -> (r: bool)\n    ensures\n        r <==> exists|i: int| 0 <= i < v.len() && v[i] == 0,\n{\n    let mut i: usize = 0;\n    while i < v.len()\n        invariant\n            0 <= i <= v.len(),\n            forall|j: int| 0 <= j < i ==> v[j] != 0,\n        decreases v.len() - i,\n    {\n        if v[i] == 0 { return true; }\n        i += 1;\n    }\n    false\n}\n"),
    problem(32, "vec_immutable", "Problem032_VecSecond.rs", "Given a borrowed Vec<u64> with at least two elements, return the second element.", "fn vec_second(v: &Vec<u64>) -> u64;", [("requires", "v.len() > 1", "second element exists"), ("ensures", "r == v[1]", "result is second element")], "requires v.len() > 1; ensures r == v[1]", "pub fn vec_second(v: &Vec<u64>) -> (r: u64)\n    requires\n        v.len() > 1,\n    ensures\n        r == v[1],\n{\n    v[1]\n}\n"),
]


P += [
    problem(33, "vec_mutation", "Problem033_VecSetAt.rs", "Given a uniquely borrowed Vec<u64>, a valid index, and a value, update exactly that element.", "fn vec_set_at(v: &mut Vec<u64>, i: usize, x: u64);", [("requires", "i < old(v).len()", "index is valid in pre-state"), ("ensures", "final(v)@ == old(v)@.update(i as int, x)", "final vector is old vector with one updated element")], "requires i < old(v).len(); ensures final(v)@ == old(v)@.update(i as int, x)", "pub fn vec_set_at(v: &mut Vec<u64>, i: usize, x: u64)\n    requires\n        i < old(v).len(),\n    ensures\n        final(v)@ == old(v)@.update(i as int, x),\n{\n    v.set(i, x);\n}\n"),
    problem(34, "vec_mutation", "Problem034_VecSwapTwo.rs", "Given a uniquely borrowed Vec<u64> and two valid indices, swap the two elements and leave all others unchanged.", "fn vec_swap_two(v: &mut Vec<u64>, i: usize, j: usize);", [("requires", "i < old(v).len()", "first index is valid"), ("requires", "j < old(v).len()", "second index is valid"), ("ensures", "final(v).len() == old(v).len()", "length is unchanged"), ("ensures", "final(v)[i as int] == old(v)[j as int]", "first position receives old second value"), ("ensures", "final(v)[j as int] == old(v)[i as int]", "second position receives old first value"), ("ensures", "forall|k:int| 0 <= k < old(v).len() && k != i && k != j ==> final(v)[k] == old(v)[k]", "other elements unchanged")], "requires i < old(v).len(); requires j < old(v).len(); ensures final(v).len() == old(v).len(); ensures final(v)[i as int] == old(v)[j as int]; ensures final(v)[j as int] == old(v)[i as int]; ensures forall other positions unchanged", "pub fn vec_swap_two(v: &mut Vec<u64>, i: usize, j: usize)\n    requires\n        i < old(v).len(),\n        j < old(v).len(),\n    ensures\n        final(v).len() == old(v).len(),\n        final(v)[i as int] == old(v)[j as int],\n        final(v)[j as int] == old(v)[i as int],\n        forall|k: int| 0 <= k < old(v).len() && k != i && k != j ==> final(v)[k] == old(v)[k],\n{\n    let x = v[i];\n    let y = v[j];\n    v.set(i, y);\n    v.set(j, x);\n}\n"),
    problem(35, "vec_mutation", "Problem035_VecPush.rs", "Given a uniquely borrowed Vec<u64> and a value, append the value to the vector.", "fn vec_push_value(v: &mut Vec<u64>, x: u64);", [("ensures", "final(v)@ == old(v)@.push(x)", "final vector is old vector with appended value")], "ensures final(v)@ == old(v)@.push(x)", "pub fn vec_push_value(v: &mut Vec<u64>, x: u64)\n    ensures\n        final(v)@ == old(v)@.push(x),\n{\n    v.push(x);\n}\n"),
    problem(36, "vec_mutation", "Problem036_VecPop.rs", "Given a nonempty uniquely borrowed Vec<u64>, pop and return the last element.", "fn vec_pop_value(v: &mut Vec<u64>) -> u64;", [("requires", "old(v).len() > 0", "vector is nonempty in pre-state"), ("ensures", "r == old(v)[old(v).len() - 1]", "result is old last element"), ("ensures", "final(v)@ == old(v)@.drop_last()", "final vector drops old last element")], "requires old(v).len() > 0; ensures r == old(v)[old(v).len() - 1]; ensures final(v)@ == old(v)@.drop_last()", "pub fn vec_pop_value(v: &mut Vec<u64>) -> (r: u64)\n    requires\n        old(v).len() > 0,\n    ensures\n        r == old(v)[old(v).len() - 1],\n        final(v)@ == old(v)@.drop_last(),\n{\n    v.pop().unwrap()\n}\n"),
    problem(37, "vec_mutation", "Problem037_VecReplaceIfInBounds.rs", "Given a uniquely borrowed Vec<u64>, index, and value, update the element only when the index is in bounds and report whether an update happened.", "fn vec_replace_if_in_bounds(v: &mut Vec<u64>, i: usize, x: u64) -> bool;", [("ensures", "final(v).len() == old(v).len()", "length unchanged"), ("ensures", "i < old(v).len() ==> r && final(v)@ == old(v)@.update(i as int, x)", "valid index updates element and returns true"), ("ensures", "i >= old(v).len() ==> !r && final(v)@ == old(v)@", "invalid index leaves vector unchanged and returns false")], "ensures final(v).len() == old(v).len(); ensures valid index updates and returns true; ensures invalid index leaves unchanged and returns false", "pub fn vec_replace_if_in_bounds(v: &mut Vec<u64>, i: usize, x: u64) -> (r: bool)\n    ensures\n        final(v).len() == old(v).len(),\n        i < old(v).len() ==> r && final(v)@ == old(v)@.update(i as int, x),\n        i >= old(v).len() ==> !r && final(v)@ == old(v)@,\n{\n    if i < v.len() {\n        v.set(i, x);\n        true\n    } else {\n        false\n    }\n}\n"),
    problem(38, "vec_mutation", "Problem038_VecPopIfNonempty.rs", "Given a uniquely borrowed Vec<u64>, pop the last element when present and return it as an Option.", "fn vec_pop_if_nonempty(v: &mut Vec<u64>) -> Option<u64>;", [("ensures", "old(v).len() == 0 ==> r is None && final(v)@ == old(v)@", "empty vector returns None unchanged"), ("ensures", "old(v).len() > 0 ==> r is Some && r->Some_0 == old(v)[old(v).len() - 1] && final(v)@ == old(v)@.drop_last()", "nonempty vector returns old last and drops it")], "ensures empty vector returns None unchanged; ensures nonempty vector returns Some old last and drops it", "pub fn vec_pop_if_nonempty(v: &mut Vec<u64>) -> (r: Option<u64>)\n    ensures\n        old(v).len() == 0 ==> r is None && final(v)@ == old(v)@,\n        old(v).len() > 0 ==> r is Some && r->Some_0 == old(v)[old(v).len() - 1] && final(v)@ == old(v)@.drop_last(),\n{\n    if v.len() == 0 { Option::None } else { Option::Some(v.pop().unwrap()) }\n}\n"),
    problem(39, "vec_mutation", "Problem039_VecPushTwo.rs", "Given a uniquely borrowed Vec<u64> and two values, append both values in order.", "fn vec_push_two(v: &mut Vec<u64>, x: u64, y: u64);", [("ensures", "final(v)@ == old(v)@.push(x).push(y)", "final vector appends x then y")], "ensures final(v)@ == old(v)@.push(x).push(y)", "pub fn vec_push_two(v: &mut Vec<u64>, x: u64, y: u64)\n    ensures\n        final(v)@ == old(v)@.push(x).push(y),\n{\n    v.push(x);\n    v.push(y);\n}\n"),
    problem(40, "vec_mutation", "Problem040_VecFillAll.rs", "Given a uniquely borrowed Vec<u64> and a value, set every element to that value.", "fn vec_fill_all(v: &mut Vec<u64>, x: u64);", [("ensures", "final(v).len() == old(v).len()", "length unchanged"), ("ensures", "forall|i:int| 0 <= i < old(v).len() ==> final(v)[i] == x", "all elements equal fill value")], "ensures final(v).len() == old(v).len(); ensures forall elements equal x", "pub fn vec_fill_all(v: &mut Vec<u64>, x: u64)\n    ensures\n        final(v).len() == old(v).len(),\n        forall|i: int| 0 <= i < old(v).len() ==> final(v)[i] == x,\n{\n    let n = v.len();\n    let mut i: usize = 0;\n    while i < n\n        invariant\n            n == v.len(),\n            0 <= i <= n,\n            forall|j: int| 0 <= j < i ==> v[j] == x,\n        decreases n - i,\n    {\n        v.set(i, x);\n        i += 1;\n    }\n}\n"),
    problem(41, "vec_mutation", "Problem041_VecZeroPrefix.rs", "Given a uniquely borrowed Vec<u64> and a valid prefix length, set the prefix to zero and leave the suffix unchanged.", "fn vec_zero_prefix(v: &mut Vec<u64>, n: usize);", [("requires", "n <= old(v).len()", "prefix length is valid"), ("ensures", "final(v).len() == old(v).len()", "length unchanged"), ("ensures", "forall|i:int| 0 <= i < n ==> final(v)[i] == 0", "prefix elements are zero"), ("ensures", "forall|i:int| n <= i < old(v).len() ==> final(v)[i] == old(v)[i]", "suffix elements unchanged")], "requires n <= old(v).len(); ensures length unchanged; ensures prefix zero; ensures suffix unchanged", "pub fn vec_zero_prefix(v: &mut Vec<u64>, n: usize)\n    requires\n        n <= old(v).len(),\n    ensures\n        final(v).len() == old(v).len(),\n        forall|i: int| 0 <= i < n ==> final(v)[i] == 0,\n        forall|i: int| n <= i < old(v).len() ==> final(v)[i] == old(v)[i],\n{\n    let mut i: usize = 0;\n    while i < n\n        invariant\n            n <= v.len(),\n            v.len() == old(v).len(),\n            0 <= i <= n,\n            forall|j: int| 0 <= j < i ==> v[j] == 0,\n            forall|j: int| i <= j < v.len() ==> v[j] == old(v)[j],\n        decreases n - i,\n    {\n        v.set(i, 0);\n        i += 1;\n    }\n}\n"),
    problem(42, "vec_mutation", "Problem042_VecCopyPrefix.rs", "Given immutable source and uniquely borrowed destination vectors where destination is long enough, copy all source elements into the destination prefix and leave the rest unchanged.", "fn vec_copy_prefix(src: &Vec<u64>, dst: &mut Vec<u64>);", [("requires", "old(dst).len() >= src.len()", "destination is long enough"), ("ensures", "final(dst).len() == old(dst).len()", "destination length unchanged"), ("ensures", "forall|i:int| 0 <= i < src.len() ==> final(dst)[i] == src[i]", "destination prefix equals source"), ("ensures", "forall|i:int| src.len() <= i < old(dst).len() ==> final(dst)[i] == old(dst)[i]", "destination suffix unchanged")], "requires old(dst).len() >= src.len(); ensures destination length unchanged; ensures prefix copied; ensures suffix unchanged", "pub fn vec_copy_prefix(src: &Vec<u64>, dst: &mut Vec<u64>)\n    requires\n        old(dst).len() >= src.len(),\n    ensures\n        final(dst).len() == old(dst).len(),\n        forall|i: int| 0 <= i < src.len() ==> final(dst)[i] == src[i],\n        forall|i: int| src.len() <= i < old(dst).len() ==> final(dst)[i] == old(dst)[i],\n{\n    let n = src.len();\n    let mut i: usize = 0;\n    while i < n\n        invariant\n            n == src.len(),\n            old(dst).len() >= n,\n            dst.len() == old(dst).len(),\n            0 <= i <= n,\n            forall|j: int| 0 <= j < i ==> dst[j] == src[j],\n            forall|j: int| i <= j < dst.len() ==> dst[j] == old(dst)[j],\n        decreases n - i,\n    {\n        let x = src[i];\n        dst.set(i, x);\n        i += 1;\n    }\n}\n"),
    problem(43, "vec_mutation", "Problem043_VecIncrementAll.rs", "Given a uniquely borrowed Vec<u64> whose elements can all be incremented, add one to every element.", "fn vec_increment_all(v: &mut Vec<u64>);", [("requires", "forall|i:int| 0 <= i < old(v).len() ==> old(v)[i] < u64::MAX", "every increment is overflow-free"), ("ensures", "final(v).len() == old(v).len()", "length unchanged"), ("ensures", "forall|i:int| 0 <= i < old(v).len() ==> final(v)[i] == old(v)[i] + 1", "every element incremented")], "requires all old elements are below u64::MAX; ensures length unchanged; ensures every element incremented", "pub fn vec_increment_all(v: &mut Vec<u64>)\n    requires\n        forall|i: int| 0 <= i < old(v).len() ==> old(v)[i] < u64::MAX,\n    ensures\n        final(v).len() == old(v).len(),\n        forall|i: int| 0 <= i < old(v).len() ==> final(v)[i] == old(v)[i] + 1,\n{\n    let n = v.len();\n    let mut i: usize = 0;\n    while i < n\n        invariant\n            n == v.len(),\n            v.len() == old(v).len(),\n            0 <= i <= n,\n            forall|j: int| 0 <= j < old(v).len() ==> old(v)[j] < u64::MAX,\n            forall|j: int| 0 <= j < i ==> v[j] == old(v)[j] + 1,\n            forall|j: int| i <= j < v.len() ==> v[j] == old(v)[j],\n        decreases n - i,\n    {\n        let x = v[i];\n        v.set(i, x + 1);\n        i += 1;\n    }\n}\n"),
    problem(44, "vec_mutation", "Problem044_VecSetFirstIfNonempty.rs", "Given a uniquely borrowed Vec<u64> and a value, set the first element only when the vector is nonempty and return whether it changed.", "fn vec_set_first_if_nonempty(v: &mut Vec<u64>, x: u64) -> bool;", [("ensures", "old(v).len() == 0 ==> !r && final(v)@ == old(v)@", "empty vector unchanged and returns false"), ("ensures", "old(v).len() > 0 ==> r && final(v)@ == old(v)@.update(0, x)", "nonempty vector updates first element and returns true")], "ensures empty unchanged false; ensures nonempty updates first true", "pub fn vec_set_first_if_nonempty(v: &mut Vec<u64>, x: u64) -> (r: bool)\n    ensures\n        old(v).len() == 0 ==> !r && final(v)@ == old(v)@,\n        old(v).len() > 0 ==> r && final(v)@ == old(v)@.update(0, x),\n{\n    if v.len() == 0 {\n        false\n    } else {\n        v.set(0, x);\n        true\n    }\n}\n"),
]


P += [
    problem(45, "ownership_slices", "Problem045_TakeVecLen.rs", "Given owned Vec<u64>, consume it and return its length.", "fn take_vec_len(v: Vec<u64>) -> usize;", [("ensures", "r == v@.len()", "result equals length of consumed vector's ghost view")], "ensures r == v@.len()", "pub fn take_vec_len(v: Vec<u64>) -> (r: usize)\n    ensures\n        r == v@.len(),\n{\n    v.len()\n}\n"),
    problem(46, "ownership_slices", "Problem046_CloneVec.rs", "Given an immutable borrowed Vec<u64>, return an owned clone with the same sequence of elements.", "fn clone_vec(v: &Vec<u64>) -> Vec<u64>;", [("ensures", "r@ == v@", "clone has same ghost sequence as input")], "ensures r@ == v@", "pub fn clone_vec(v: &Vec<u64>) -> (r: Vec<u64>)\n    ensures\n        r@ == v@,\n{\n    v.clone()\n}\n"),
    problem(47, "ownership_slices", "Problem047_SliceLen.rs", "Given an immutable slice of u64, return its length without indexing.", "fn slice_len(s: &[u64]) -> usize;", [("ensures", "r == s.len()", "result is executable slice length"), ("ensures", "r == s@.len()", "result is ghost sequence length")], "ensures r == s.len(); ensures r == s@.len()", "pub fn slice_len(s: &[u64]) -> (r: usize)\n    ensures\n        r == s.len(),\n        r == s@.len(),\n{\n    s.len()\n}\n"),
    problem(48, "ownership_slices", "Problem048_SliceFirst.rs", "Given a nonempty immutable slice of u64, return its first element.", "fn slice_first(s: &[u64]) -> u64;", [("requires", "s.len() > 0", "slice is nonempty"), ("ensures", "r == s[0]", "result is first slice element")], "requires s.len() > 0; ensures r == s[0]", "pub fn slice_first(s: &[u64]) -> (r: u64)\n    requires\n        s.len() > 0,\n    ensures\n        r == s[0],\n{\n    s[0]\n}\n"),
    problem(49, "ownership_slices", "Problem049_ArrayGet3.rs", "Given a borrowed fixed-size array of length three and a valid index, return the indexed element.", "fn array_get3(a: &[u64; 3], i: usize) -> u64;", [("requires", "i < 3", "index is valid for length-three array"), ("ensures", "r == a@[i as int]", "result is indexed array element")], "requires i < 3; ensures r == a@[i as int]", "pub fn array_get3(a: &[u64; 3], i: usize) -> (r: u64)\n    requires\n        i < 3,\n    ensures\n        r == a@[i as int],\n{\n    a[i]\n}\n"),
    problem(50, "ownership_slices", "Problem050_ArraySet3.rs", "Given a uniquely borrowed fixed-size array of length three, valid index, and value, update exactly that array position.", "fn array_set3(a: &mut [u64; 3], i: usize, x: u64);", [("requires", "i < 3", "index is valid for length-three array"), ("ensures", "final(a)@ == old(a)@.update(i as int, x)", "final array is old array with indexed value updated")], "requires i < 3; ensures final(a)@ == old(a)@.update(i as int, x)", "pub fn array_set3(a: &mut [u64; 3], i: usize, x: u64)\n    requires\n        i < 3,\n    ensures\n        final(a)@ == old(a)@.update(i as int, x),\n{\n    a[i] = x;\n}\n"),
]


def main() -> None:
    for d in [GT, REQ]:
        d.mkdir(parents=True, exist_ok=True)

    requirements = []
    ground_truth = []
    for p in P:
        rel = f"{p['category']}/{p['filename']}"
        out_dir = GT / p["category"]
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / p["filename"]).write_text(PRELUDE + p["body"] + POSTLUDE, encoding="utf-8")

        requirements.append({
            "id": p["id"],
            "path": rel,
            "category": p["category"],
            "requirement_en": p["requirement_en"],
        })
        ground_truth.append({
            "id": p["id"],
            "path": rel,
            "category": p["category"],
            "requirement_en": p["requirement_en"],
            "ground_truth_file": f"benchmarks/rust-verus-problems/ground-truth/{rel}",
            "ground_truth_source": "manual",
            "verifier": "verus",
            "function_signature": p["function_signature"],
            "ground_truth_clauses": [
                {
                    "id": f"gt{i}",
                    "type": kind,
                    "expr": expr,
                    "text": text,
                    "source": "manual_verus_ground_truth",
                }
                for i, (kind, expr, text) in enumerate(p["clauses"], start=1)
            ],
            "ground_truth_contract": p["contract"],
        })

    (REQ / "requirements_50.json").write_text(json.dumps(requirements, indent=2) + "\n", encoding="utf-8")
    (REQ / "requirements_50_ground_truth_specs.json").write_text(json.dumps(ground_truth, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
